# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-05-12 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name=b'date viewed')),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(0, b'0'), (1, b'1')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productviews.Product')),
            ],
        ),
    ]
