# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-05-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
